const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Behaviors.Rex_MoveTo,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.Flash,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Browser,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.HTMLElement,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Plugins.Function,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.lunarray_LiteTween.Acts.Reverse,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Rex_MoveTo.Acts.SetTargetPosOnObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Rex_MoveTo.Acts.SetEnabled,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.SetProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.AddProbabilityEntry,
		C3.Plugins.AdvancedRandom.Exps.Weighted,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Behaviors.lunarray_LiteTween.Acts.SetEasing,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportbottom
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{gameScreen: 0},
	{Background: 0},
	{Sine: 0},
	{Title: 0},
	{Start: 0},
	{opened: 0},
	{Settings: 0},
	{Music: 0},
	{LiteTween: 0},
	{snowFrame: 0},
	{Esmaecer: 0},
	{Spaces: 0},
	{ice: 0},
	{slice01_2: 0},
	{slice02_: 0},
	{Progress: 0},
	{Acheived_Stars: 0},
	{slice04_: 0},
	{Available: 0},
	{Hammer: 0},
	{Mega_Bomb: 0},
	{arrowPowerup: 0},
	{slice03_3: 0},
	{slice09_: 0},
	{slice10_: 0},
	{snowBlock: 0},
	{Bullet: 0},
	{Wrap: 0},
	{snow: 0},
	{snowflake: 0},
	{tree: 0},
	{trees: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Matched: 0},
	{Moving: 0},
	{trigger: 0},
	{row: 0},
	{col: 0},
	{dy: 0},
	{color: 0},
	{targetY: 0},
	{State: 0},
	{Rotate: 0},
	{Resize: 0},
	{Fade: 0},
	{Donuts: 0},
	{Effect: 0},
	{Touch: 0},
	{Mouse: 0},
	{Áudio: 0},
	{Array: 0},
	{Marker: 0},
	{SwapData: 0},
	{MoveTo: 0},
	{MiniStar_03: 0},
	{MiniStar_02: 0},
	{MiniStar_01: 0},
	{Stars_Magnet: 0},
	{Selection: 0},
	{Selector: 0},
	{Selector2: 0},
	{CircleGems: 0},
	{points: 0},
	{Score: 0},
	{Progress_Bar: 0},
	{Arrow_Destroyer: 0},
	{Hammer_Destroyer: 0},
	{type: 0},
	{TXT: 0},
	{Text_error_api: 0},
	{loading: 0},
	{bt_sound: 0},
	{Senóide: 0},
	{bt_automatico: 0},
	{bt_mais: 0},
	{bt_menos: 0},
	{txt_creditos: 0},
	{txt_aposta_total: 0},
	{Piscar: 0},
	{txt_balance: 0},
	{txt_BET: 0},
	{bt_play: 0},
	{txt_automatico: 0},
	{txt_premios: 0},
	{txt_premio: 0},
	{bt_home: 0},
	{config_jogadas: 0},
	{bt_fechar_configjogadas: 0},
	{contagem_automatico: 0},
	{contagem_automatico2: 0},
	{bt_start_automatico: 0},
	{local: 0},
	{controle: 0},
	{Sensor_automatico: 0},
	{Back: 0},
	{DragDrop: 0},
	{Button: 0},
	{Bar: 0},
	{Button2: 0},
	{Navegador: 0},
	{Grey: 0},
	{bt_config: 0},
	{config: 0},
	{bt_fechar: 0},
	{bt_musica: 0},
	{bt_som: 0},
	{txt_multiplier: 0},
	{txt_premios2: 0},
	{txt_roundID: 0},
	{AleatoriedadeAvançada: 0},
	{comprar_rodadas_gratis: 0},
	{Sprite_rodadas: 0},
	{txt_freeSpin_en: 0},
	{txts_bonus_en: 0},
	{txt_comprar_rodadas: 0},
	{score2: 0},
	{Size: 0},
	{Hearts: 0},
	{ElementoHTML: 0},
	{bt_buy_rodadas: 0},
	{Sprite3: 0},
	{txt_lucky: 0},
	{ganhou_bonus: 0},
	{sprite_fundo_info: 0},
	{ganhou_rodadas_gratis: 0},
	{Atrelar: 0},
	{txt_ganhou_rodadas: 0},
	{winner_rodadas: 0},
	{txt_total_rodadas: 0},
	{txt_total_winner: 0},
	{Function: 0},
	{mini: 0},
	{LiteTween2: 0},
	{rodadas_gratis: 0},
	{Max_Time: 0},
	{Timer: 0},
	{CY: 0},
	{CX: 0},
	{Scoring: 0},
	{Blocks: 0},
	{Moves: 0},
	{Trigger: 0},
	{Matches: 0},
	{FirstPiece: 0},
	{MovingBlocks: 0},
	{TILE: 0},
	{apiUrl: 0},
	{accountid: 0},
	{apiversion: 0},
	{gamesessionid: 0},
	{currency: 0},
	{lang: 0},
	{request: 0},
	{bonusbalance: 0},
	{roundid: 0},
	{ACCOUNTTRANSACTIONID: 0},
	{log: 0},
	{ultima_chamada: 0},
	{exiturl: 0},
	{layoult_name: 0},
	{balance: 0},
	{rc: 0},
	{betAmount: 0},
	{resultAmount: 0},
	{situacao_aposta: 0},
	{betlimits: 0},
	{betlimits1: 0},
	{betlimits2: 0},
	{betlimits3: 0},
	{betlimits4: 0},
	{betlimits5: 0},
	{divisor: 0},
	{Multiplier: 0},
	{sound: 0},
	{automatico: 0},
	{automatico_ativo: 0},
	{Phase: 0},
	{som: 0},
	{musica: 0},
	{Speed: 0},
	{MATCH: 0},
	{Wineffect: 0},
	{bonusgame: 0},
	{Explosions: 0},
	{Freespins: 0},
	{Buyspins: 0},
	{betBuy: 0},
	{totalrodadas: 0},
	{total_winner_rodadas: 0},
	{Lucky: 0},
	{janela_rodadas_gratis: 0},
	{Value: 0},
	{comprourodadas: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	gameScreen: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	Start: class extends self.ISpriteInstance {},
	Settings: class extends self.ISpriteInstance {},
	Music: class extends self.ISpriteInstance {},
	snowFrame: class extends self.ISpriteInstance {},
	Spaces: class extends self.ISpriteInstance {},
	ice: class extends self.ISpriteInstance {},
	slice01_2: class extends self.ISpriteInstance {},
	slice02_: class extends self.ISpriteInstance {},
	Acheived_Stars: class extends self.ISpriteInstance {},
	slice04_: class extends self.ISpriteInstance {},
	Hammer: class extends self.ISpriteInstance {},
	Mega_Bomb: class extends self.ISpriteInstance {},
	arrowPowerup: class extends self.ISpriteInstance {},
	slice03_3: class extends self.ISpriteInstance {},
	slice09_: class extends self.ISpriteInstance {},
	slice10_: class extends self.ISpriteInstance {},
	snowBlock: class extends self.ISpriteInstance {},
	snow: class extends self.ISpriteInstance {},
	snowflake: class extends self.ISpriteInstance {},
	tree: class extends self.ISpriteInstance {},
	trees: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Donuts: class extends self.ISpriteInstance {},
	Effect: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	Marker: class extends self.ISpriteInstance {},
	SwapData: class extends self.IArrayInstance {},
	MiniStar_03: class extends self.ISpriteInstance {},
	MiniStar_02: class extends self.ISpriteInstance {},
	MiniStar_01: class extends self.ISpriteInstance {},
	Stars_Magnet: class extends self.ISpriteInstance {},
	Selection: class extends self.ISpriteInstance {},
	Selector: class extends self.ISpriteInstance {},
	Selector2: class extends self.ISpriteInstance {},
	CircleGems: class extends self.ISpriteInstance {},
	points: class extends self.ITextInstance {},
	Score: class extends self.ITextInstance {},
	Progress_Bar: class extends self.ITiledBackgroundInstance {},
	Arrow_Destroyer: class extends self.ISpriteInstance {},
	Hammer_Destroyer: class extends self.ISpriteInstance {},
	TXT: class extends self.ITextInstance {},
	Text_error_api: class extends self.ITextInstance {},
	loading: class extends self.ISpriteInstance {},
	bt_sound: class extends self.ISpriteInstance {},
	bt_automatico: class extends self.ISpriteInstance {},
	bt_mais: class extends self.ISpriteInstance {},
	bt_menos: class extends self.ISpriteInstance {},
	txt_creditos: class extends self.ITextInstance {},
	txt_aposta_total: class extends self.ITextInstance {},
	txt_balance: class extends self.ITextInstance {},
	txt_BET: class extends self.ITextInstance {},
	bt_play: class extends self.ISpriteInstance {},
	txt_automatico: class extends self.ITextInstance {},
	txt_premios: class extends self.ITextInstance {},
	txt_premio: class extends self.ITextInstance {},
	bt_home: class extends self.ISpriteInstance {},
	config_jogadas: class extends self.ISpriteInstance {},
	bt_fechar_configjogadas: class extends self.ISpriteInstance {},
	contagem_automatico: class extends self.ISpriteInstance {},
	contagem_automatico2: class extends self.ISpriteInstance {},
	bt_start_automatico: class extends self.ISpriteInstance {},
	Sensor_automatico: class extends self.ISpriteInstance {},
	Back: class extends self.ISpriteInstance {},
	Button: class extends self.ISpriteInstance {},
	Bar: class extends self.ITiledBackgroundInstance {},
	Button2: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	Grey: class extends self.ISpriteInstance {},
	bt_config: class extends self.ISpriteInstance {},
	config: class extends self.ISpriteInstance {},
	bt_fechar: class extends self.ISpriteInstance {},
	bt_musica: class extends self.ISpriteInstance {},
	bt_som: class extends self.ISpriteInstance {},
	txt_multiplier: class extends self.ITextInstance {},
	txt_premios2: class extends self.ITextInstance {},
	txt_roundID: class extends self.ITextInstance {},
	AleatoriedadeAvançada: class extends self.IInstance {},
	comprar_rodadas_gratis: class extends self.ISpriteInstance {},
	Sprite_rodadas: class extends self.ISpriteInstance {},
	txt_freeSpin_en: class extends self.ISpriteInstance {},
	txts_bonus_en: class extends self.ISpriteInstance {},
	txt_comprar_rodadas: class extends self.ITextInstance {},
	score2: class extends self.ITextInstance {},
	Hearts: class extends self.ISpriteInstance {},
	ElementoHTML: class extends self.IHTMLElementInstance {},
	bt_buy_rodadas: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	txt_lucky: class extends self.ITextInstance {},
	ganhou_bonus: class extends self.ISpriteInstance {},
	sprite_fundo_info: class extends self.ISpriteInstance {},
	ganhou_rodadas_gratis: class extends self.ISpriteInstance {},
	txt_ganhou_rodadas: class extends self.ISpriteFontInstance {},
	winner_rodadas: class extends self.ISpriteInstance {},
	txt_total_rodadas: class extends self.ISpriteFontInstance {},
	txt_total_winner: class extends self.ITextInstance {},
	Function: class extends self.IInstance {},
	mini: class extends self.ISpriteInstance {},
	rodadas_gratis: class extends self.ISpriteInstance {}
}